### ISSUE TITLE
Problem sending the value 751619276800 in the CC-Total-Octets AVP

### ISSUE THREAD

**Issue by luisfilsilva** [node-diameter/node-diameter#75]
Hi guys,

I'm sending a CCR with the CC-Total-Octets AVP with a value of 751619276800 (700GB). What I'm seeing is that the library is considering this AVP Uint32, when in fact, it is supposed to be consider Unsigned64. Because of this, I'm getting an exception when attempting to send it. Do you know why?

Thanks,
Luís

        {
            "code": 421,
            "name": "CC-Total-Octets",
            "vendorId": 0,
            "type": "Unsigned64",
            "flags": {
                "mandatory": true,
                "protected": false,
                "mayEncrypt": false,
                "vendorBit": false
            }
        },

---

Multiple-Services-Credit-Control: 
  Rating-Group: 12804
  Service-Identifier: 16
  Requested-Service-Unit: 
    CC-Total-Octets: 751619276800

--------------------------------------------------------------------------------

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 751_619_276_800
    at checkInt (internal/buffer.js:63:11)
    at writeU_Int32BE (internal/buffer.js:793:3)
    at Buffer.writeUInt32BE (internal/buffer.js:806:10)
    at Object.encode (/scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-types.js:53:24)
    at Object.exports.encode (/scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-types.js:148:26)
    at encodeAvp (/scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-codec.js:327:39)
    at /scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-codec.js:280:16
    at arrayMap (/scratch/home/brmadmin/lsilva/node-diameter-master/node_modules/lodash/lodash.js:639:23)
    at Function.map (/scratch/home/brmadmin/lsilva/node-diameter-master/node_modules/lodash/lodash.js:9554:14)
    at encodeAvps (/scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-codec.js:279:24)
    at encodeAvp (/scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-codec.js:298:25)
    at /scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-codec.js:280:16
    at arrayMap (/scratch/home/brmadmin/lsilva/node-diameter-master/node_modules/lodash/lodash.js:639:23)
    at Function.map (/scratch/home/brmadmin/lsilva/node-diameter-master/node_modules/lodash/lodash.js:9554:14)
    at encodeAvps (/scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-codec.js:279:24)
    at encodeAvp (/scratch/home/brmadmin/lsilva/node-diameter-master/lib/diameter-codec.js:298:25)

**Comment by luisfilsilva** [comment]
After doing some reverse Eng, I guess I need to send Long format, right? 

Thanks!!
Luís

**Comment by atesgoral** [comment]
@luisfilsilva Yeah, you need to use a `Long` instance. Let's close this ticket if using Long fixed your problem.

**Comment by luisfilsilva** [comment]
Yes, it has fixed the issue!! Thanks!!
